### ISSUE TITLE
An error occured while appending TPM values to the final output files

### ISSUE THREAD

**Issue by sunsong95** [icbi-lab/NeoFuse#15]
Hi，the following error occurs when I run NeoFuse
`NeoFuse -1 /home/myname/data/neoantigen/1.fastq.gz -2 /home/myname/data/neoantigen/2.fastq.gz -s /home/myname/ref/neofuse/STAR_idx/ -g /home/myname/ref/neofuse/GRCh37.p13.genome.fa -a /home/myname/ref/neofuse/gencode.v19.annotation.gtf -m 8 -M 10 -n 20 --docker`
```
[07:25:55]  Paired End (PE) Reads detected: commencing processing
[07:25:55]  Processing files 1.fastq.gz - 2.fastq.gz
[07:25:55]  STAR Run started
[07:25:55]  Arriba Run started
[08:08:59]  YARA Run started
[08:18:39]  OptiType Run started
[08:32:28]  featureCounts Run started
[08:33:47]  Converting Raw Counts to TPM and FPKM
[08:33:48]  Searching for peptides of length 8 9 10
[08:33:48]  MHCFlurry Run started
[08:41:12]  Creating Final Ouptut
An error occured while appending TPM values to the final output files, check final.log for more details
```

this is final.log:
```
Traceback (most recent call last):
  File "/usr/local/bin/source/final_out.py", line 155, in <module>
    desperation(inFile1, inFile2, outFile)
  File "/usr/local/bin/source/final_out.py", line 80, in desperation
    if "NA" in gene1tpm[i].split("\t")[1] or "NA" in gene2tpm[i].split("\t")[1]:
IndexError: list index out of range
```
Do you have any suggestion?
Thanks！

**Comment by abyssum** [comment]
Hello @sunsong95 ,

First of all, thank you for taking an interest in NeoFuse, and sorry for the late reply (I was out of the office on vacation).
Judging by your error, there seems to be an issue with some of your output files and since I am unable to reproduce your error locally, I would need some of your output files if possible.
1. The `*_tmp_filtered.tsv` which should be found in dir: `/path/to/run_ID/NeoFuse/`
2. The `*.tpm.txt` which should be found under: ` /path/to/run_ID/TPM/`

I would also suggest using the output (`-o`) and run ID (`-t`) flags since your samples are named 1, 2 and this might lead to filename collisions.

**Comment by abyssum** [comment]
Since I don't have any updates on this issue I will close the thread.
