### ISSUE TITLE
 IndexError in final_out.py When Processing TPM Values

### ISSUE THREAD

**Issue by zdq0808** [icbi-lab/NeoFuse#21]
Hello, Fotakis.

I am using neofuse and I encountered an IndexError during the execution of the script `final_out.py`. The error occurs when the script attempts to access elements in a list that appears to be shorter than expected.

**Error Message:**

**Traceback (most recent call last):
  File "/usr/local/bin/source/final_out.py", line 155, in <module>
    desperation(inFile1, inFile2, outFile)
  File "/usr/local/bin/source/final_out.py", line 80, in desperation
    if "NA" in gene1tpm[i].split("\t")[1] or "NA" in gene2tpm[i].split("\t")[1]:
IndexError: list index out of range；**

**Possible Fix:**
It may be helpful to add checks before accessing list elements to ensure that the length of the split results meets the expected number of elements.

I am happy to provide further details or assist in testing any fixes. Thank you for looking into this issue.

Dongqiang

**Comment by abyssum** [comment]
Hello @DongqiangZeng0808,

First of all, thank you for using NeoFuse.

We are currently migrating NeoFuse to Nextflow's DSL2 and in a short time we will release a new version - supporting MHC class II neoantigens as well. Since the current version of NeoFuse will become obsolete with the new release, we are no longer actively developing this version (sorry for the inconvenience).

In the meantime, can you check if you can find and forward the following files:
1.  `/path/to/output/TPM/<sample>.tpm.txt`
2. `/path/to/output/NeoFuse/<sample>_tmp_filtered.tsv`

and i will try to look into it as soon as I have some time.
